#!/usr/bin/env python3
"""Generate Class IX (SSC-I, Sindh) Math target-content PDF.

The scanned textbook Math IX (1) (1).pdf has almost no extractable text, so RAG
cannot ground Learning Chat practice MCQs. This script writes a selectable-text
target PDF whose UNIT headings match the Sindh Class IX table of contents.

Upload this PDF as the diagnostic target content PDF. After a student is weak on
a diagnostic topic, User AI generates practice MCQs from the matching unit.
"""
from __future__ import annotations

import os
import textwrap

import pymupdf

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "sample_pdfs", "math_ix")

MARGIN_LEFT = 52
MARGIN_TOP = 52
LINE_HEIGHT = 13
FONT_SIZE = 10
PAGE_WIDTH = 595
PAGE_HEIGHT = 842
MAX_Y = PAGE_HEIGHT - 48
WRAP = 96


def _new_writer() -> tuple[pymupdf.Document, pymupdf.Page, float]:
    doc = pymupdf.open()
    page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
    return doc, page, float(MARGIN_TOP)


def _write_line(doc: pymupdf.Document, page: pymupdf.Page, y: float, text: str) -> tuple[pymupdf.Page, float]:
    if y > MAX_Y:
        page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
        y = float(MARGIN_TOP)
    page.insert_text((MARGIN_LEFT, y), text, fontsize=FONT_SIZE, fontname="helv")
    return page, y + LINE_HEIGHT


def _write_lines(doc: pymupdf.Document, page: pymupdf.Page, y: float, lines: list[str]) -> tuple[pymupdf.Page, float]:
    for raw in lines:
        wrapped = textwrap.wrap(raw, width=WRAP) if raw.strip() else [""]
        for piece in wrapped:
            page, y = _write_line(doc, page, y, piece)
    return page, y


def _save_doc(doc: pymupdf.Document, path: str) -> int:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    total_chars = sum(len(p.get_text()) for p in doc)
    page_count = doc.page_count
    doc.save(path)
    doc.close()
    print(f"Saved {path}  pages={page_count}  extractable_chars={total_chars}")
    return total_chars


def target_content_lines() -> list[str]:
    return [
        "Grade 9 Mathematics - Target Content PDF",
        "Class: IX / SSC-I  |  Board: Sindh Textbook Board  |  Standard: Class 9",
        "Source curriculum: The Textbook of Mathematics for Class IX (Sindh, 2024)",
        "Purpose: Learning Chat weak-area practice. If a student is weak on a diagnostic topic,",
        "User AI must generate Class IX practice MCQs from the matching UNIT section below.",
        "",
        "How to use: keep UNIT headings exactly as written so RAG can match diagnostic topics.",
        "Do not invent Class 10 or university content. Stay at SSC-I / Class 9 standard.",
        "",
        "=" * 72,
        "UNIT 1: Real and Complex Numbers",
        "=" * 72,
        "Topics: Real Numbers, Rational Numbers, Irrational Numbers, Radicals, Exponents, Complex Numbers",
        "Exam weightage: 7%",
        "",
        "Real numbers R are the union of rational numbers Q and irrational numbers Q'.",
        "R = Q union Q'. Every real number can be placed on the number line.",
        "",
        "Rational number: a number that can be written as a/b where a, b are integers and b is not 0.",
        "Examples: 3, -4, 2/5, 0.75, 0.333... (terminating or recurring decimals).",
        "Irrational number: cannot be written as a/b. Decimal is non-terminating and non-recurring.",
        "Examples: sqrt(2), sqrt(3), pi, cube root of 5.",
        "",
        "Number sets: N = {1,2,3,...}, W = {0,1,2,...}, Z = {...,-2,-1,0,1,2,...}.",
        "Prime numbers: 2, 3, 5, 7, ...  Composite numbers: 4, 6, 8, 9, 10, ...",
        "Even integers: ..., -4, -2, 0, 2, 4, ...   Odd integers: ..., -3, -1, 1, 3, ...",
        "",
        "Properties of real numbers: commutative, associative, distributive, additive identity 0,",
        "multiplicative identity 1, additive inverse -a, multiplicative inverse 1/a if a is not 0.",
        "",
        "Radicals: in n-th root of a, a is the radicand and n is the index.",
        "Radical to exponent: n-th root of a = a^(1/n).  sqrt(a) = a^(1/2).",
        "Example: cube root of 8 = 8^(1/3) = 2.",
        "",
        "Laws of exponents (a > 0): a^m * a^n = a^(m+n), a^m / a^n = a^(m-n), (a^m)^n = a^(mn),",
        "a^0 = 1, a^(-n) = 1/a^n, (ab)^n = a^n b^n, (a/b)^n = a^n / b^n.",
        "Example: 2^3 * 2^2 = 2^5 = 32.   Example: 9^(1/2) = 3.",
        "",
        "Complex number: z = a + ib where a is the real part, b is the imaginary part, i^2 = -1.",
        "Also written as ordered pair (a, b). Conjugate of z is z-bar = a - ib.",
        "Equality: a+ib = c+id if and only if a = c and b = d.",
        "Addition: (a+ib) + (c+id) = (a+c) + i(b+d).",
        "Subtraction: (a+ib) - (c+id) = (a-c) + i(b-d).",
        "Multiplication: (a+ib)(c+id) = (ac-bd) + i(ad+bc).",
        "Division: multiply numerator and denominator by the conjugate of the denominator.",
        "Example: (3+2i) + (1-4i) = 4 - 2i.",
        "Example: (2+3i)(1-i) = 2 - 2i + 3i - 3i^2 = 2 + i + 3 = 5 + i.",
        "Common mistake: treating i as a variable instead of using i^2 = -1.",
        "",
        "=" * 72,
        "UNIT 2: Logarithms",
        "=" * 72,
        "Topics: Scientific Notation, Logarithms, Common Logarithm, Natural Logarithm, Antilogarithm",
        "Exam weightage: 5%",
        "",
        "Scientific notation: a number is written as m x 10^n where 1 <= m < 10 and n is an integer.",
        "Example: 45000 = 4.5 x 10^4.   Example: 0.0032 = 3.2 x 10^(-3).",
        "",
        "Definition: if a^x = y with a > 0, a not equal to 1, and y > 0, then log_a(y) = x.",
        "So logarithm is the exponent. Example: 2^3 = 8 means log_2(8) = 3.",
        "",
        "Common logarithm: base 10. Written log y or log10 y.  log10 y = x means y = 10^x.",
        "Natural logarithm: base e. Written ln y.  ln y = x means y = e^x.",
        "",
        "Characteristic and mantissa (common log): log N = characteristic + mantissa.",
        "For N >= 1, characteristic = (number of digits left of decimal) minus 1.",
        "For 0 < N < 1, characteristic is negative (bar notation). Mantissa is always non-negative.",
        "Example: log 345.2 has characteristic 2 because 345.2 has 3 digits before the decimal.",
        "Antilogarithm: if log N = x then N = antilog(x). Use log tables or a calculator.",
        "",
        "Laws of logarithms:",
        "1) log_a(mn) = log_a m + log_a n",
        "2) log_a(m/n) = log_a m - log_a n",
        "3) log_a(m^n) = n log_a m",
        "4) Change of base: log_a n = log_b n / log_b a. Also log_a m * log_m n = log_a n.",
        "Example: log 2 + log 5 = log 10 = 1 (common log).",
        "Example: log 1000 = 3 because 10^3 = 1000.",
        "Example: ln e^4 = 4.",
        "Common mistake: writing log(m+n) as log m + log n. That law is for products, not sums.",
        "",
        "=" * 72,
        "UNIT 3: Algebraic Expression and Formulas",
        "=" * 72,
        "Topics: Algebraic Expressions, Rational Expressions, Algebraic Formulas, Polynomials",
        "Exam weightage: 9%",
        "",
        "Polynomial: sum of terms a_n x^n + ... + a1 x + a0 with non-negative integer powers.",
        "x^2 + 3x + 1 is a polynomial.  1/x and sqrt(x) are not polynomials.",
        "Rational expression: p(x)/q(x) where p and q are polynomials and q is not the zero polynomial.",
        "Lowest form: numerator and denominator have no common factor other than 1 or -1.",
        "Example: (x^2 - 1)/(x-1) = (x-1)(x+1)/(x-1) = x+1, provided x is not 1.",
        "",
        "Operations: add/subtract after a common denominator. Multiply numerators and denominators.",
        "Divide by multiplying by the reciprocal. Always reduce to lowest form.",
        "Numerical value: substitute the given real number. Example: if x=2, 3x^2 - 1 = 11.",
        "",
        "Identities:",
        "(a+b)^2 = a^2 + 2ab + b^2",
        "(a-b)^2 = a^2 - 2ab + b^2",
        "(a+b)^2 + (a-b)^2 = 2(a^2 + b^2)",
        "(a+b)^2 - (a-b)^2 = 4ab",
        "(a+b+c)^2 = a^2 + b^2 + c^2 + 2ab + 2bc + 2ca",
        "",
        "If a+b = 5 and a-b = 1 then 2(a^2+b^2) = 25+1 = 26 so a^2+b^2 = 13, and 4ab = 25-1 = 24 so ab = 6.",
        "If a+b+c = 6 and ab+bc+ca = 11 then a^2+b^2+c^2 = (a+b+c)^2 - 2(ab+bc+ca) = 36 - 22 = 14.",
        "Common mistake: expanding (a+b)^2 as a^2 + b^2 and forgetting 2ab.",
        "",
        "=" * 72,
        "UNIT 4: Factorization",
        "=" * 72,
        "Topics: Factorization, Remainder Theorem, Factor Theorem, Synthetic Division, Cubic Polynomials",
        "Exam weightage: 9%",
        "",
        "Common factor: ka + kb + kc = k(a+b+c).",
        "Grouping: ac + ad + bc + bd = a(c+d) + b(c+d) = (a+b)(c+d).",
        "Perfect square: a^2 + 2ab + b^2 = (a+b)^2 and a^2 - 2ab + b^2 = (a-b)^2.",
        "Difference of squares: a^2 - b^2 = (a-b)(a+b).",
        "Example: x^2 - 9 = (x-3)(x+3).  Example: x^2 + 6x + 9 = (x+3)^2.",
        "",
        "Quadratic trinomial: x^2 + px + q = (x+m)(x+n) where m+n = p and mn = q.",
        "Example: x^2 + 7x + 12 = (x+3)(x+4).",
        "ax^2 + bx + c: find two numbers whose product is ac and sum is b, then split the middle term.",
        "Example: 2x^2 + 7x + 3 = 2x^2 + 6x + x + 3 = 2x(x+3) + 1(x+3) = (2x+1)(x+3).",
        "",
        "Cubes: a^3 + b^3 = (a+b)(a^2 - ab + b^2).  a^3 - b^3 = (a-b)(a^2 + ab + b^2).",
        "(a+b)^3 = a^3 + 3a^2 b + 3ab^2 + b^3.  (a-b)^3 = a^3 - 3a^2 b + 3ab^2 - b^3.",
        "Example: x^3 - 8 = (x-2)(x^2 + 2x + 4).",
        "",
        "Remainder theorem: remainder when p(x) is divided by (x-a) is p(a).",
        "Example: p(x)=x^2-3x+2 divided by x-1: remainder p(1)=0.",
        "Zero of a polynomial: a number r such that p(r)=0. Then (x-r) is a factor (factor theorem).",
        "Synthetic division: a short method to divide by a linear factor x-a.",
        "To factor a cubic, test possible zeros, then use factor theorem and divide.",
        "Common mistake: using p(-a) when dividing by x+a. For x+a = x-(-a), remainder is p(-a).",
        "",
        "=" * 72,
        "UNIT 5: Algebraic Manipulation",
        "=" * 72,
        "Topics: HCF, LCM, Algebraic Manipulation, Square Root of Algebraic Expressions",
        "Exam weightage: 5%",
        "",
        "HCF (highest common factor) of algebraic expressions: product of common factors with lowest powers.",
        "LCM (least common multiple): product of all factors with highest powers.",
        "Relation: HCF(A,B) x LCM(A,B) = A x B for two expressions.",
        "",
        "Example: A = 12 x^2 y, B = 18 x y^3.",
        "HCF = 6 x y.  LCM = 36 x^2 y^3.  Check: 6xy * 36 x^2 y^3 = 216 x^3 y^4 and A*B = 216 x^3 y^4.",
        "",
        "Division method (Euclidean idea): HCF(A,B) = HCF(B, remainder of A divided by B), repeat.",
        "Reduce a fractional expression using HCF of numerator and denominator.",
        "Addition of fractions: common denominator is the LCM of the denominators.",
        "",
        "Square root by factorization: sqrt(a^2 b^2) = |ab|. For polynomials, write as a perfect square.",
        "Example: sqrt(x^2 + 6x + 9) = sqrt((x+3)^2) = |x+3|.",
        "Division method for square roots of algebraic expressions follows the same pairing idea as numbers.",
        "Common mistake: taking HCF as the product of highest powers. Highest powers belong to LCM.",
        "",
        "=" * 72,
        "UNIT 6: Linear Equation and Inequalities",
        "=" * 72,
        "Topics: Linear Equations, Absolute Value, Linear Inequalities",
        "Exam weightage: 6%",
        "",
        "Linear equation in one variable: ax + b = 0 with a not 0. Solution x = -b/a.",
        "With rational coefficients, clear fractions by multiplying through by the LCM of denominators.",
        "Example: 3x + 7 = 22 => 3x = 15 => x = 5.",
        "Example: (x/2) + 1 = 4 => x/2 = 3 => x = 6.",
        "",
        "Equations with radicals: isolate the radical, square both sides, then check for extraneous roots.",
        "Example: sqrt(x+3) = 2 => x+3 = 4 => x = 1. Check: sqrt(4)=2, valid.",
        "",
        "Absolute value: |x| is x if x >= 0 and -x if x < 0. Geometrically, distance from 0.",
        "|A| = b with b >= 0 means A = b or A = -b.",
        "Example: |x-2| = 5 => x-2 = 5 or x-2 = -5 => x = 7 or x = -3.",
        "If |A| = negative number, there is no solution.",
        "",
        "Inequalities: <, >, <=, >=. Trichotomy: for real a,b one of a<b, a=b, a>b is true.",
        "Transitive: a<b and b<c implies a<c.",
        "Adding the same number to both sides preserves the inequality.",
        "Multiplying or dividing by a positive number preserves it.",
        "Multiplying or dividing by a negative number reverses the inequality.",
        "Example: -2x < 6 => x > -3 (divided by -2, sign reversed).",
        "Example: 2x + 1 <= 7 => 2x <= 6 => x <= 3.",
        "Common mistake: forgetting to reverse the inequality when multiplying by a negative.",
        "",
        "=" * 72,
        "UNIT 7: Linear Graphs and their Applications",
        "=" * 72,
        "Topics: Linear Graphs, Ordered Pairs, Cartesian Plane, Simultaneous Linear Equations",
        "Exam weightage: 5%",
        "",
        "Ordered pair (a,b): a is the x-coordinate (abscissa), b is the y-coordinate (ordinate).",
        "(2,5) is not the same as (5,2).",
        "Cartesian plane: x-axis (horizontal) and y-axis (vertical) meet at origin O(0,0) at right angles.",
        "Quadrant I: (+,+), II: (-,+), III: (-,-), IV: (+,-).",
        "",
        "Linear equation in two variables: ax + by + c = 0. Its graph is a straight line.",
        "y = c is a horizontal line. x = a is a vertical line.",
        "y = mx has slope m and passes through the origin.",
        "y = mx + c has slope m and y-intercept c.",
        "To graph: make a table of at least two points, plot, and join with a straight line.",
        "Example: y = 2x + 1. When x=0, y=1. When x=1, y=3. Line through (0,1) and (1,3).",
        "",
        "Conversion graphs: two quantities in direct proportion give a straight line through a scale.",
        "Examples: miles and kilometres, Celsius and Fahrenheit, PKR and another currency.",
        "Read one quantity from the other using the graph.",
        "",
        "Simultaneous linear equations graphically: the intersection point is the common solution.",
        "If lines are parallel, no solution. If they coincide, infinitely many solutions.",
        "Example: x+y=4 and x-y=2 intersect at (3,1).",
        "Common mistake: swapping abscissa and ordinate when plotting (a,b).",
        "",
        "=" * 72,
        "UNIT 8: Quadratic Equations",
        "=" * 72,
        "Topics: Quadratic Equations, Factorization of Quadratics, Completing the Square, Quadratic Formula",
        "Exam weightage: 8%",
        "",
        "Quadratic equation: ax^2 + bx + c = 0 with a not 0. Degree is 2.",
        "A linear equation has degree 1. x^3 + 1 = 0 is cubic, not quadratic.",
        "",
        "Solve by factorization: factor, then set each factor equal to zero.",
        "Example: x^2 - 9 = 0 => (x-3)(x+3)=0 => x=3 or x=-3.",
        "Example: x^2 + 7x + 12 = 0 => (x+3)(x+4)=0 => x=-3 or x=-4.",
        "",
        "Completing the square: x^2 + bx = (x + b/2)^2 - (b/2)^2, then take square roots.",
        "Example: x^2 + 6x + 5 = 0 => (x+3)^2 = 4 => x+3 = 2 or x+3 = -2 => x=-1 or x=-5.",
        "",
        "Quadratic formula (derived by completing the square): x = [-b ± sqrt(b^2 - 4ac)] / (2a).",
        "Discriminant D = b^2 - 4ac.",
        "D > 0: two distinct real roots. D = 0: one repeated real root. D < 0: no real roots.",
        "Example: x^2 + 6x + 9 = 0 has D = 36-36 = 0, one root x = -3.",
        "",
        "Equations reducible to quadratic: let y = x^2 in ax^4 + bx^2 + c = 0.",
        "Reciprocal type: let y = x + 1/x when the equation has x^2 + 1/x^2 and x + 1/x.",
        "Remember x^2 + 1/x^2 = (x + 1/x)^2 - 2.",
        "Radical equations: isolate, square, then reject extra roots that fail the original equation.",
        "Common mistake: forgetting the ± when taking square roots, or keeping roots that make a square root negative.",
        "",
        "=" * 72,
        "UNIT 9: Congruent Triangles",
        "=" * 72,
        "Topics: Congruent Triangles, SSS, SAS, ASA, AAS, RHS, Isosceles Triangle",
        "Exam weightage: 7%",
        "",
        "Two triangles are congruent if one can be placed on the other so that all corresponding sides",
        "and angles match. Corresponding parts of congruent triangles are equal (CPCT).",
        "",
        "SSS: three sides of one equal to three corresponding sides of the other.",
        "SAS: two sides and the included angle.",
        "ASA: two angles and the included side.",
        "AAS: two angles and a non-included corresponding side.",
        "RHS (right-hypotenuse-side): in right triangles, hypotenuse and one leg.",
        "",
        "Isosceles triangle theorem: if two angles are equal, the sides opposite them are equal.",
        "Converse: if two sides are equal, the angles opposite them are equal.",
        "Base angles of an isosceles triangle are equal.",
        "",
        "Example: in triangle ABC, AB=AC and angle B = angle C. The triangle is isosceles.",
        "Example: two right triangles with hypotenuse 13 and one leg 5 are congruent by RHS if those",
        "parts correspond.",
        "Common mistake: AAA shows similarity, not congruence. Equal angles alone do not fix size.",
        "",
        "=" * 72,
        "UNIT 10: Parallelograms and Triangles",
        "=" * 72,
        "Topics: Parallelograms, Midpoint Theorem, Medians, Concurrent Lines",
        "Exam weightage: 7%",
        "",
        "A parallelogram is a quadrilateral with both pairs of opposite sides parallel.",
        "Properties: opposite sides are equal; opposite angles are equal; diagonals bisect each other.",
        "Consecutive angles are supplementary (sum 180 degrees).",
        "If one pair of opposite sides is equal and parallel, the quadrilateral is a parallelogram.",
        "",
        "Midpoint theorem: the segment joining midpoints of two sides of a triangle is parallel to the",
        "third side and half as long.",
        "Example: in triangle ABC, M and N midpoints of AB and AC. Then MN is parallel to BC and MN = BC/2.",
        "",
        "Medians: a median joins a vertex to the midpoint of the opposite side.",
        "The three medians are concurrent at the centroid. The centroid divides each median in ratio 2:1,",
        "with the longer part toward the vertex (point of trisection of the median).",
        "",
        "If three or more parallel lines cut congruent intercepts on one transversal, they cut congruent",
        "intercepts on any other transversal.",
        "Common mistake: thinking diagonals of a parallelogram are equal. That is true for a rectangle.",
        "",
        "=" * 72,
        "UNIT 11: Line Bisectors and Angles Bisectors",
        "=" * 72,
        "Topics: Perpendicular Bisector, Angle Bisector, Circumcentre, Incentre",
        "Exam weightage: 7%",
        "",
        "Right bisector (perpendicular bisector) of segment AB: the line through the midpoint of AB",
        "and perpendicular to AB.",
        "Any point on the right bisector is equidistant from A and B.",
        "Converse: any point equidistant from A and B lies on the right bisector of AB.",
        "The perpendicular bisectors of the sides of a triangle are concurrent at the circumcentre,",
        "the centre of the circumcircle (circle through all three vertices).",
        "",
        "Angle bisector: a ray that splits an angle into two equal angles.",
        "Any point on the angle bisector is equidistant from the two arms of the angle.",
        "Converse: a point inside the angle that is equidistant from the arms lies on the bisector.",
        "The angle bisectors of a triangle are concurrent at the incentre, centre of the incircle",
        "(circle touching all three sides).",
        "",
        "Example: if P is on the perpendicular bisector of AB then PA = PB.",
        "Example: if a point is 4 cm from both arms of an angle, it lies on the angle bisector.",
        "Common mistake: mixing circumcentre (perpendicular bisectors) with incentre (angle bisectors).",
        "",
        "=" * 72,
        "UNIT 12: Sides and Angles of a Triangle",
        "=" * 72,
        "Topics: Triangle Inequality, Sides and Angles of a Triangle",
        "Exam weightage: 5%",
        "",
        "In a triangle, a longer side lies opposite a greater angle.",
        "If two sides are unequal, the angle opposite the longer side is greater.",
        "If two angles are unequal, the side opposite the greater angle is longer.",
        "",
        "Triangle inequality: the sum of any two sides is greater than the third side.",
        "Also: the difference of two sides is less than the third side.",
        "Example: sides 3, 4, 5 work because 3+4>5, 3+5>4, 4+5>3.",
        "Example: 2, 3, 6 cannot form a triangle because 2+3 is not greater than 6.",
        "",
        "The perpendicular from a point to a line is the shortest distance from that point to the line.",
        "Any other segment from the point to the line is longer than the perpendicular.",
        "",
        "In a right triangle, the hypotenuse is the longest side (it is opposite the greatest angle, 90).",
        "Common mistake: accepting 2, 3, 5 as a triangle. 2+3=5, so the points are collinear, not a triangle.",
        "",
        "=" * 72,
        "UNIT 13: Practical Geometry - Triangles",
        "=" * 72,
        "Topics: Practical Geometry, Construction of Triangles, Altitudes, Medians, Angle Bisectors",
        "Exam weightage: 3%",
        "",
        "A triangle can be constructed uniquely when you are given:",
        "- two sides and the included angle (SAS),",
        "- one side and two angles (ASA or AAS),",
        "- SSS (three sides, if they satisfy triangle inequality).",
        "SSA (two sides and a non-included angle) can give 0, 1, or 2 triangles (ambiguous case).",
        "",
        "In a given triangle you can construct:",
        "angle bisectors (meet at incentre), altitudes (meet at orthocentre),",
        "perpendicular bisectors (meet at circumcentre), medians (meet at centroid).",
        "",
        "Area constructions (Class IX practical geometry):",
        "Construct a triangle equal in area to a given quadrilateral.",
        "Construct a rectangle equal in area to a given triangle.",
        "Construct a square equal in area to a given rectangle.",
        "Construct a triangle of the same area on a given base.",
        "Key idea: triangles or parallelograms on the same base and between the same parallels have",
        "equal area, so you can slide a vertex along a parallel line without changing area.",
        "Common mistake: treating SSA as always unique like SAS.",
        "",
        "=" * 72,
        "UNIT 14: Theorems Related with Area",
        "=" * 72,
        "Topics: Area of Parallelogram, Area of Triangle, Theorems Related with Area",
        "Exam weightage: 5%",
        "",
        "Area of parallelogram = base x corresponding height.",
        "Area of triangle = (1/2) x base x height.",
        "",
        "Parallelograms on the same base and between the same parallel lines have equal area.",
        "Parallelograms on equal bases and having the same altitude have equal area.",
        "Triangles on the same base and of the same altitude have equal area.",
        "Triangles on equal bases and of the same altitude have equal area.",
        "",
        "A triangle and a parallelogram on the same base and between the same parallels:",
        "area of triangle is half the area of the parallelogram.",
        "",
        "Example: parallelograms ABCD and EFCD stand on the same base CD and between the same parallels;",
        "their areas are equal even if the slanted sides look different.",
        "Example: triangles with base 10 and height 6 both have area 30, even if they are not congruent.",
        "Common mistake: thinking equal area means congruent. Equal area does not mean same shape.",
        "",
        "=" * 72,
        "UNIT 15: Projection of a side of a Triangle",
        "=" * 72,
        "Topics: Projection of a Side of a Triangle, Pythagoras Theorem, Apollonius Theorem",
        "Exam weightage: 7%",
        "",
        "The projection of side AC on side AB is the segment from A to the foot of the perpendicular",
        "from C to line AB. In right triangle ABC with right angle at C, projection ideas recover Pythagoras.",
        "",
        "Pythagoras (right triangle, right angle at C): a^2 + b^2 = c^2 where c is the hypotenuse.",
        "Example: 3-4-5 triangle: 9+16=25.",
        "",
        "Obtuse-angled case: if angle C is obtuse, then AB^2 = AC^2 + BC^2 + 2 BC x (projection of AC on BC).",
        "The square on the side opposite the obtuse angle is greater than the sum of the other two squares.",
        "",
        "Acute-angled case: the square on the side opposite an acute angle equals the sum of the squares",
        "on the other two sides minus twice one of those sides times the projection of the other on it.",
        "",
        "Apollonius theorem: in any triangle, AB^2 + AC^2 = 2 AD^2 + 2 BD^2 where D is the midpoint of BC",
        "(AD is a median). In words: sum of squares of two sides = twice the square of half the third",
        "side plus twice the square of the median to that side.",
        "Example: if BC=10 then BD=5. If median AD=6 and AB=8, AC=8 (isosceles), check 64+64 = 2(36)+2(25)=122.",
        "Common mistake: applying a^2+b^2=c^2 to a non-right triangle.",
        "",
        "=" * 72,
        "UNIT 16: Introduction to Coordinate Geometry / Analytical Geometry",
        "=" * 72,
        "Topics: Coordinate Geometry, Distance Formula, Midpoint Formula, Collinear Points",
        "Exam weightage: 5%",
        "",
        "Coordinate geometry (analytical geometry) studies geometry using the Cartesian plane.",
        "Collinear points lie on one straight line. Non-collinear points do not.",
        "",
        "Distance between A(x1,y1) and B(x2,y2):",
        "AB = sqrt( (x2-x1)^2 + (y2-y1)^2 ).",
        "Example: distance from (1,2) to (4,6) = sqrt(3^2 + 4^2) = sqrt(25) = 5.",
        "",
        "Three points A,B,C are collinear if AB + BC = AC (largest segment equals the sum of the other two).",
        "You can also check that the area of triangle ABC is 0.",
        "",
        "Classify triangle ABC using distances:",
        "equilateral: all three sides equal;",
        "isosceles: exactly two sides equal;",
        "scalene: all sides different;",
        "right-angled: the sides satisfy Pythagoras (largest side is hypotenuse).",
        "",
        "Classify quadrilateral ABCD using distances (and optionally diagonals):",
        "square: four equal sides and equal diagonals;",
        "rectangle: opposite sides equal and diagonals equal;",
        "parallelogram: both pairs of opposite sides equal (diagonals need not be equal).",
        "",
        "Midpoint of A(x1,y1) and B(x2,y2) is ( (x1+x2)/2 , (y1+y2)/2 ).",
        "Example: midpoint of (2,3) and (6,7) is (4,5).",
        "The midpoint of a parallelogram's diagonal pair is the same point (diagonals bisect each other).",
        "Common mistake: using (x2-x1, y2-y1) as the midpoint instead of the averages.",
        "",
        "END OF TARGET CONTENT",
        "",
        "Teacher note: generate Class IX practice MCQs only from the UNIT that matches the weak topic.",
        "Use the worked examples and formulas in that unit. Keep four options A B C D and one correct answer.",
    ]


def diagnostic_qa_lines() -> list[str]:
    return [
        "Grade 9 Mathematics - Diagnostic Assessment",
        "Class: IX / SSC-I Sindh | Topics match the Class IX target content PDF",
        "Total: 32 Multiple Choice Questions (2 per unit)",
        "INSTRUCTIONS: Choose the best answer (A, B, C, or D).",
        "",
        "=" * 60,
        "UNIT 1: Real and Complex Numbers",
        "=" * 60,
        "1. Which number is irrational?",
        "   A) 0.75",
        "   B) 2/7",
        "   C) sqrt(2)",
        "   D) 4",
        "2. The conjugate of 3 - 5i is:",
        "   A) 3 + 5i",
        "   B) -3 - 5i",
        "   C) 5 - 3i",
        "   D) -3 + 5i",
        "",
        "=" * 60,
        "UNIT 2: Logarithms",
        "=" * 60,
        "3. log10 1000 equals:",
        "   A) 2",
        "   B) 3",
        "   C) 10",
        "   D) 100",
        "4. log 2 + log 5 (common log) equals:",
        "   A) log 7",
        "   B) log 3",
        "   C) 1",
        "   D) 10",
        "",
        "=" * 60,
        "UNIT 3: Algebraic Expression and Formulas",
        "=" * 60,
        "5. Which is a polynomial?",
        "   A) 1/x + 2",
        "   B) x^2 + 3x + 1",
        "   C) sqrt(x) + 1",
        "   D) 2^x",
        "6. If a+b=5 and a-b=1, then ab equals:",
        "   A) 4",
        "   B) 5",
        "   C) 6",
        "   D) 13",
        "",
        "=" * 60,
        "UNIT 4: Factorization",
        "=" * 60,
        "7. x^2 + 7x + 12 factors as:",
        "   A) (x+2)(x+6)",
        "   B) (x+3)(x+4)",
        "   C) (x+1)(x+12)",
        "   D) (x-3)(x-4)",
        "8. Remainder when x^2 - 3x + 2 is divided by x-1 is:",
        "   A) 0",
        "   B) 1",
        "   C) 2",
        "   D) -1",
        "",
        "=" * 60,
        "UNIT 5: Algebraic Manipulation",
        "=" * 60,
        "9. HCF of 12 x^2 y and 18 x y^3 is:",
        "   A) 36 x^2 y^3",
        "   B) 6 x y",
        "   C) 12 x y",
        "   D) 3 x^2 y^3",
        "10. For two expressions, HCF x LCM equals:",
        "    A) HCF + LCM",
        "    B) the larger expression",
        "    C) product of the two expressions",
        "    D) 1",
        "",
        "=" * 60,
        "UNIT 6: Linear Equation and Inequalities",
        "=" * 60,
        "11. Solve 3x + 7 = 22.",
        "    A) x=3",
        "    B) x=5",
        "    C) x=7",
        "    D) x=15",
        "12. Solving -2x < 6 gives:",
        "    A) x < -3",
        "    B) x > -3",
        "    C) x < 3",
        "    D) x > 3",
        "",
        "=" * 60,
        "UNIT 7: Linear Graphs and their Applications",
        "=" * 60,
        "13. The graph of x = 3 is:",
        "    A) a horizontal line",
        "    B) a vertical line",
        "    C) a line through origin with slope 3",
        "    D) the x-axis",
        "14. Point (2,-5) lies in quadrant:",
        "    A) I",
        "    B) II",
        "    C) III",
        "    D) IV",
        "",
        "=" * 60,
        "UNIT 8: Quadratic Equations",
        "=" * 60,
        "15. Solve x^2 - 9 = 0.",
        "    A) x=3 only",
        "    B) x=-3 only",
        "    C) x=3 or x=-3",
        "    D) x=9 or x=-9",
        "16. Discriminant of x^2 + 6x + 9 = 0 is:",
        "    A) -36",
        "    B) 0",
        "    C) 9",
        "    D) 36",
        "",
        "=" * 60,
        "UNIT 9: Congruent Triangles",
        "=" * 60,
        "17. Which condition proves congruence of right triangles using hypotenuse and one leg?",
        "    A) SSS",
        "    B) ASA",
        "    C) RHS",
        "    D) AAA",
        "18. AAA for two triangles shows:",
        "    A) congruence always",
        "    B) similarity, not necessarily congruence",
        "    C) equal area only",
        "    D) they are right triangles",
        "",
        "=" * 60,
        "UNIT 10: Parallelograms and Triangles",
        "=" * 60,
        "19. Diagonals of a parallelogram:",
        "    A) are always equal",
        "    B) bisect each other",
        "    C) are always perpendicular",
        "    D) never intersect",
        "20. Midpoint theorem: the segment joining midpoints of two sides is:",
        "    A) equal to the third side",
        "    B) perpendicular to the third side",
        "    C) parallel to the third side and half as long",
        "    D) twice the third side",
        "",
        "=" * 60,
        "UNIT 11: Line Bisectors and Angles Bisectors",
        "=" * 60,
        "21. A point on the perpendicular bisector of AB is:",
        "    A) closer to A than to B",
        "    B) equidistant from A and B",
        "    C) the midpoint of AB only",
        "    D) on line AB",
        "22. Angle bisectors of a triangle meet at the:",
        "    A) centroid",
        "    B) orthocentre",
        "    C) circumcentre",
        "    D) incentre",
        "",
        "=" * 60,
        "UNIT 12: Sides and Angles of a Triangle",
        "=" * 60,
        "23. Which lengths can be sides of a triangle?",
        "    A) 2, 3, 6",
        "    B) 3, 4, 5",
        "    C) 1, 2, 3",
        "    D) 5, 1, 1",
        "24. In a triangle, the side opposite the greatest angle is:",
        "    A) the shortest side",
        "    B) the longest side",
        "    C) a median",
        "    D) always the base",
        "",
        "=" * 60,
        "UNIT 13: Practical Geometry - Triangles",
        "=" * 60,
        "25. SAS construction uses:",
        "    A) three sides",
        "    B) two sides and the included angle",
        "    C) two angles and no side",
        "    D) hypotenuse only",
        "26. Medians of a triangle are concurrent at the:",
        "    A) incentre",
        "    B) circumcentre",
        "    C) centroid",
        "    D) orthocentre",
        "",
        "=" * 60,
        "UNIT 14: Theorems Related with Area",
        "=" * 60,
        "27. Area of a triangle with base 10 and height 6 is:",
        "    A) 16",
        "    B) 30",
        "    C) 60",
        "    D) 120",
        "28. Parallelograms on the same base and between the same parallels have:",
        "    A) equal perimeters",
        "    B) equal areas",
        "    C) equal diagonals",
        "    D) congruent shapes",
        "",
        "=" * 60,
        "UNIT 15: Projection of a side of a Triangle",
        "=" * 60,
        "29. In a right triangle with legs 3 and 4, the hypotenuse is:",
        "    A) 5",
        "    B) 6",
        "    C) 7",
        "    D) 12",
        "30. Pythagoras a^2 + b^2 = c^2 applies when the triangle is:",
        "    A) any triangle",
        "    B) equilateral only",
        "    C) right-angled",
        "    D) obtuse only",
        "",
        "=" * 60,
        "UNIT 16: Introduction to Coordinate Geometry / Analytical Geometry",
        "=" * 60,
        "31. Distance between (1,2) and (4,6) is:",
        "    A) 4",
        "    B) 5",
        "    C) 6",
        "    D) 7",
        "32. Midpoint of (2,3) and (6,7) is:",
        "    A) (4,4)",
        "    B) (4,5)",
        "    C) (8,10)",
        "    D) (3,4)",
        "",
        "=" * 60,
        "ANSWER KEY",
        "=" * 60,
        "1 C  sqrt(2) is irrational",
        "2 A  conjugate of a+ib is a-ib, so 3+5i",
        "3 B  10^3 = 1000",
        "4 C  log 10 = 1",
        "5 B  non-negative integer powers only",
        "6 C  4ab = (a+b)^2 - (a-b)^2 = 24, ab=6",
        "7 B  3+4=7 and 3*4=12",
        "8 A  p(1)=0",
        "9 B  common lowest powers: 6xy",
        "10 C HCF*LCM = product",
        "11 B 3x=15, x=5",
        "12 B divide by -2, reverse inequality",
        "13 B x=constant is vertical",
        "14 D (+,-) is quadrant IV",
        "15 C x=±3",
        "16 B D=36-36=0",
        "17 C RHS",
        "18 B AAA is similarity",
        "19 B diagonals bisect each other",
        "20 C parallel and half",
        "21 B equidistant from endpoints",
        "22 D incentre",
        "23 B 3+4>5",
        "24 B longest side opposite greatest angle",
        "25 B two sides and included angle",
        "26 C centroid",
        "27 B (1/2)*10*6=30",
        "28 B equal areas",
        "29 A 9+16=25",
        "30 C right-angled only",
        "31 B sqrt(9+16)=5",
        "32 B averages (4,5)",
        "",
        "END OF DIAGNOSTIC",
    ]


def build_pdf(path: str, lines: list[str]) -> int:
    doc, page, y = _new_writer()
    page, y = _write_lines(doc, page, y, lines)
    return _save_doc(doc, path)


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    target_path = os.path.join(OUT_DIR, "target_content_math_ix_sindh.pdf")
    diag_path = os.path.join(OUT_DIR, "diagnostic_qa_math_ix_sindh.pdf")
    desktop_copy = os.path.join(ROOT, "target_content_math_ix_sindh.pdf")

    target_chars = build_pdf(target_path, target_content_lines())
    diag_chars = build_pdf(diag_path, diagnostic_qa_lines())

    # Easy-to-find copy next to the original scanned textbook.
    import shutil

    shutil.copy2(target_path, desktop_copy)
    print(f"Copied target PDF to {desktop_copy}")

    if target_chars < 8000:
        raise SystemExit(f"ERROR: target PDF too thin ({target_chars} chars).")
    if diag_chars < 2000:
        raise SystemExit(f"ERROR: diagnostic PDF too thin ({diag_chars} chars).")
    print("OK: text-based Class IX target + diagnostic PDFs are ready.")


if __name__ == "__main__":
    main()
